update tess-suite to fail on faileure

diff --git a/.github/workflows/tests-suite.yml b/.github/workflows/tests-suite.yml
--- a/.github/workflows/tests-suite.yml
+++ b/.github/workflows/tests-suite.yml
@@ -11,7 +11,7 @@ on:
       - staging
 
 jobs:
-  tests-suite:
+  tests-suite-by-version:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -19,17 +19,26 @@ jobs:
     steps:
     - name: Checkout repository
       uses: actions/checkout@v3
-
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: ${{ matrix.python-version }}
-
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install pytest
-
     - name: Run tests
       run: |
         pytest tests
+  tests-suite:
+    runs-on: ubuntu-latest
+    needs: tests-suite-by-version
+    steps:
+    - name: Check status of tests-suite-by-version
+      run: |
+        if [ "${{ needs.tests-suite-by-version.outcome }}" != "success" ]; then
+          echo "Previous job(s) failed."
+          exit 1
+        else
+          echo "All previous jobs passed."
+        fi
